### ISSUE TITLE
Error message when sending variable to the console from visualea

### ISSUE THREAD

**Issue by cokelaer** [openalea/openalea#113]
The variable is put in the shell/console and can be accessed normally but there is an error message printed

```
Traceback (most recent call last):
  File "/home/cokelaer/Work/virtualenv/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<string>", line 1
    print 'c'
```

**Comment by gbaty** [comment]
#125 seems to fix this bug

**Comment by pradal** [comment]
Sure,I have not see this bug report.
But I have the same problem and I fix the bug.
Cheers
