### ISSUE TITLE
Functions defined in Python model ignore global variables

### ISSUE THREAD

**Issue by gbaty** [openalea/openalea#171]
Example:

```python
a=1
def f():
    print a
  
f()
```

Raises
```bash
Traceback (most recent call last):
  File "IPython/core/interactiveshell.py", line 3033, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-b37ac6ab9fd9>", line 5, in <module>
    f()
  File "<ipython-input-1-b37ac6ab9fd9>", line 3, in f
    print a
NameError: global name 'a' is not defined
```

**Comment by gbaty** [comment]
A unit test yet exists but has never been fixed.
See [test_model.py:276](https://github.com/openalea/openalea/blob/master/core/test/test_model.py#L276).

**Comment by gbaty** [comment]
As user_ns was redefined in Project.start, user_ns and global_ns were no more linked and so, global_variables were ignored.
