### ISSUE TITLE
Bug OAlab: spurious dependency on tissuelab

### ISSUE THREAD

**Issue by revesansparole** [openalea/openalea#200]
Lancement de OAlab, OK
Un seul lab dispo sur splashscreen, IPython, OK
menu file - New project: Error
Traceback (most recent call last):
  File "c:\users\administrateur\desktop\jerome\dvlpt\branchs\openalea\oalab\src\openalea\oalab\project\projectwidget.py", line 452, in new_project
    project_creator = CreateProjectWidget()
  File "c:\users\administrateur\desktop\jerome\dvlpt\branchs\openalea\oalab\src\openalea\oalab\project\creator.py", line 52, in **init**
    self.editor_name = widget('IStr', name)
  File "c:\users\administrateur\desktop\jerome\dvlpt\branchs\openalea\oalab\src\openalea\oalab\service\qt_control.py", line 65, in widget
    return qt_editor(control, shape, preferred)
  File "c:\users\administrateur\desktop\jerome\dvlpt\branchs\openalea\oalab\src\openalea\oalab\service\qt_control.py", line 94, in qt_editor
    widget_class = qt_editor_class(control.interface, shape, preferred)
  File "c:\users\administrateur\desktop\jerome\dvlpt\branchs\openalea\oalab\src\openalea\oalab\service\qt_control.py", line 57, in qt_editor_class
    widget_class = plugin.load()
  File "c:\users\administrateur\desktop\jerome\dvlpt\branchs\openalea\oalab\src\openalea\oalab\plugins\controls__init__.py", line 133, in load
    from openalea.oalab.plugins.controls.widgets import StrLineEdit
  File "c:\users\administrateur\desktop\jerome\dvlpt\branchs\openalea\oalab\src\openalea\oalab\plugins\controls\widgets.py", line 518, in <module>
    import tissuelab
ImportError: No module named tissuelab

While I assume installing tissuelab will solve the probleme, I'm not sure it is the expected behaviour.

**Comment by gbaty** [comment]
openalea must not depend on tissuelab. Will be fixed soon.

**Comment by gbaty** [comment]
Fixed in commit oalab_1x/0827943

**Comment by pradal** [comment]
Fixed in current version
