### ISSUE TITLE
Bug OAlab: in drag and drop

### ISSUE THREAD

**Issue by revesansparole** [openalea/openalea#201]
Installed "trunk" version of openalea.core and openalea.oalab.
Tried to drag the "startup" icon and I got this error message:
Traceback (most recent call last):
  File "c:\users\administrateur\desktop\jerome\dvlpt\openalea\oalab\src\openalea\oalab\project\projectwidget.py", line 602, in startDrag
    obj = self._model._project.get(category, name)
  File "c:\users\administrateur\desktop\jerome\dvlpt\openalea\core\src\core\project\project.py", line 241, in get
    return self.get_item(category, name)
  File "c:\users\administrateur\desktop\jerome\dvlpt\openalea\core\src\core\project\project.py", line 387, in get_item
    files = getattr(self, category)
  File "c:\users\administrateur\desktop\jerome\dvlpt\openalea\core\src\core\project\project.py", line 170, in __getattr__
    return super(Project, self).__getattribute__(key)
AttributeError: 'Project' object has no attribute 'category'

**Comment by revesansparole** [comment]
same problem with:
"doc"
"lib"

**Comment by gbaty** [comment]
What is "trunk" version ? Do you mean old svn "trunk" or "master" branch ?

**Comment by revesansparole** [comment]
Sorry, didn't find my words. I meant "master" branch of openalea github repo (hence the "" around the trunk in my previous message :)

**Comment by gbaty** [comment]
ok. no problem. Much more clear ;)
(note: you can use "git branch" to know the name of your current branch)

**Comment by gbaty** [comment]
Fixed in branch oalab_1.x
