### ISSUE TITLE
No dialog if user add a data and a data with same name yet exists

### ISSUE THREAD

**Issue by gbaty** [openalea/openalea#207]
Right exception is raised but result is not user friendly.

Traceback (most recent call last):
  File ".../openalea/oalab/src/openalea/oalab/project/projectbrowser.py", line 355, in open
    project.add(name, path=p)
  File ".../openalea/core/src/core/project/project.py", line 243, in add
    return self.add_item(category, obj, **kwargs)
  File ".../openalea/core/src/core/project/project.py", line 349, in add_item
    data = self._add_item(category, obj, **kwargs)
  File ".../openalea/core/src/core/project/project.py", line 319, in _add_item
    return self._add_item(category, data_obj, **kwargs)
  File ".../openalea/core/src/core/project/project.py", line 264, in _add_item
    raise ValueError("data '%s' already exists in project '%s'" % (obj.filename, self.alias))
ValueError: data 'filename' already exists in project 'MyProject'

**Comment by gbaty** [comment]
Two possible solution:
   - create a CustomException, catch it and display it with "make_error_dialog"
   - prevent it and allow user to change name with a dialog
