### ISSUE TITLE
Tests fail in openalea.core

### ISSUE THREAD

**Issue by revesansparole** [openalea/openalea#208]
running test suite with just openalea.core installed leads to 22 errors and 2 failures.
These arise certainly due to the fact that no other components were installed (i.e. oalab or vpltk)

error: no vpltk
Failure: ImportError (No module named vpltk.check.ipython) ... ERROR
Failure: ImportError (No module named vpltk.check.ipython) ... ERROR
Failure: ImportError (No module named vpltk.check.ipython) ... ERROR

error: no oalab
Failure: ImportError (No module named oalab.model.parse) ... ERROR
# test_plugin.test2 ... ERROR
## ERROR: test_plugin.test2

Traceback (most recent call last):
  File "c:\users\jerome\desktop\venv\oa\lib\site-packages\nose\case.py", line 19
7, in runTest
    self.test(*self.arg)
  File "C:\Users\jerome\Desktop\dvlpt\openalea\core\test\test_plugin.py", line 9
, in test2
    myentrypoint = plugins['oalab']
KeyError: 'oalab'
# failures:
## FAIL: test_plugin.test1

Traceback (most recent call last):
  File "c:\users\jerome\desktop\venv\oa\lib\site-packages\nose\case.py", line 19
7, in runTest
    self.test(*self.arg)
  File "C:\Users\jerome\Desktop\dvlpt\openalea\core\test\test_plugin.py", line 5
, in test1
    assert 'oalab' in plugins
AssertionError
# 
## FAIL: test_plugin_proxy (test_pluginmanager.TestPluginManager)

Traceback (most recent call last):
  File "C:\Users\jerome\Desktop\dvlpt\openalea\core\test\test_pluginmanager.py",
 line 224, in test_plugin_proxy
    assert w1
AssertionError

---

**Comment by gbaty** [comment]
These tests are obsolete because plugin are now managed by pluginmanager and plugin services. All tests on plugins are now in "test_pluginmanager" and has no more dependencies to oalab. All theses topics are already fixed in development branch.

**Comment by pradal** [comment]
With the big split (#244) all these circular dependencies have been removed (core do not depends any more of oalab and vpltk).
