### ISSUE TITLE
python setup.py fail

### ISSUE THREAD

**Issue by revesansparole** [openalea/openalea#223]
while python multisetup.py still pass!

**Comment by revesansparole** [comment]
Only on Conda

**Comment by revesansparole** [comment]
How to reproduce (on Windows assuming you are in a dvlpt directory that contain both, deploy, sconsx and openalea directory)

conda create -y -n oatoto python
activate oatoto

conda install -y scons
conda install -y pywin32

cd deploy
python setup.py develop
cd ..

cd sconsx
python setup.py develop
cd ..

cd openalea
python setup.py develop


ERROR MESSAGE
[oatoto] C:\Users\jerome\Desktop\dvlpt\openalea>python setup.py develop
Install OpenAlea.Deploy first
cannot import name Multisetup
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    main()
  File "C:\Users\jerome\Desktop\dvlpt\openalea\multisetup.py", line 68, in main
    mysetup = Multisetup(curdir='.', commands=args, packages=dirs)
NameError: global name 'Multisetup' is not defined
