### ISSUE TITLE
Using conda virtual envs fails on MacOSX (Sierra FYI)

### ISSUE THREAD

**Issue by jwintz** [openalea/openalea#234]
Hello,

To get a minimal development environment in order to work with openalea packages and extensions, we have created the following conda environment specification:

```
name: virtual-plants
channels:
  - openalea
  - defaults
dependencies:
  - python=2.7
  - ipython-qtconsole=3.2.1
  - jinja2
  - numpy
  - scipy
  - matplotlib=1.5.1
  - vtk
  - openalea.sconsx
  - pip:
      - pyqode.python
```

The later is installed using 

    conda env create -f virtual-plants.yml

And is activated by

    source activate virtual-plants

So far so good. Now in order to place ourselves into a development context we explicitly clone the relevant repositories:
- openalea
- openalea-components
- openalea-cellcomplex
- openalea-tissuelab

For each of them we use either the

    python mutisetup.py develop # for openalea and openalea-components

or

    python setup.py develop # for openalea-cellcomplex and openalea-tissuelab

This procedure works fine with environments on Linux, but fails on MacOS with the following trace.

```
Entering misc package
Python exec :  /Users/jwintz/.conda/envs/virtual-plants/bin/python
Reading metainfo 
...version: 1.3.0
...release: 1.3
...project: openalea
...name: OpenAlea.Misc
...namespace: openalea
...pkg_name: openalea.misc
...package: misc
...description: Miscellaneous tools for OpenAlea administration.
...long_description: 
...authors: OpenAlea consortium, Christophe Pradal, Thomas Cokelaer
...authors_email: christophe pradal at cirad fr, Thomas Cokelaer at sophia inria fr
...url: http://openalea.gforge.inria.fr
...license: Cecill-C
running develop
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    "openalea.misc= openalea.misc_wralea",
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 52, in finalize_options
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 273, in finalize_options
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1323, in _expand
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/site-packages/openalea/deploy/command.py", line 654, in finalize_options
    self.install_dyn_lib = get_dyn_lib_dir()
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/site-packages/openalea/deploy/install_lib.py", line 71, in get_dyn_lib_dir
    return get_default_dyn_lib()
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/site-packages/openalea/deploy/install_lib.py", line 53, in get_default_dyn_lib
    env_dir = os.path.abspath(os.environ['PREFIX'])
  File "/Users/jwintz/.conda/envs/virtual-plants/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'PREFIX'
	Executing /Users/jwintz/.conda/envs/virtual-plants/bin/python setup.py develop --prefix=/Users/jwintz/.conda/envs/virtual-plants/ ...processing
```

Note that using

    export PREFIX=$CONDA_PREFIX

has no effect whatsoever.

Any hints ?

Thanks.

  - ju

**Comment by jwintz** [comment]
Update: I got visualea working with the aforementioned setup but using:

    export PREFIX=$CONDA_ENV_PATH

However, tissuelab keeps failing with the following output:

    openalea.core.manager.UnknownItemError: Item TestApplet not found in oalab.applet

**Comment by pradal** [comment]
There is a bug.
If you build the packages from conda-build system, the PREFIX variable is set:
http://conda.pydata.org/docs/building/environment-vars.html

However, in your case, we are in a conda environment with a package built without the conda build system.
I need to figure out how to detect this case. 

For the second error, I can not reproduce it.
TestApplet is defined in oalab/testing/applet.py

But it is not defined as an entry_point (setup.py).
Can you give me the error stack?
Cheers

**Comment by jwintz** [comment]
Here is the full trace:

```
✗ jwintz@oniris ~/Development $ source activate virtual-plants
discarding /Users/jwintz/.conda/bin from PATH
prepending /Users/jwintz/.conda/envs/virtual-plants/bin to PATH
✓ jwintz@oniris ~/Development [virtual-plants] $ oalab -e tissue
PyQt4 used: your application or derivative works must be released under GPL or CeCILL license !
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/Users/jwintz/.conda/envs/virtual-plants/bin/oalab", line 11, in <module>
    load_entry_point('OpenAlea.OALab', 'gui_scripts', 'oalab')()
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/main.py", line 98, in main
    win = launch_lab(plugin_class)
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/main.py", line 43, in launch_lab
    win = OALabMainWin(lab=lab_class, autosave=True)
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/widget/splittablewindow.py", line 985, in __init__
    splittable.fromJSON(layout)
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/widget/splittablewindow.py", line 880, in fromJSON
    g.visit_i_breadth_first(visitor)
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/widget/splitterui.py", line 337, in visit_i_breadth_first
    ignoreFirst, ignoreSecond = visitor.visit(currNode)
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/widget/splittablewindow.py", line 770, in visit
    widget = self._to_qwidget(widget)
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/widget/splittablewindow.py", line 760, in _to_qwidget
    container.add_applets(applets)
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/widget/splittablewindow.py", line 660, in add_applets
    self._tabwidget.set_applet(name, properties=properties)
  File "/Users/jwintz/Development/openalea/oalab/src/openalea/oalab/widget/splittablewindow.py", line 431, in set_applet
    applet = plugin_instance('oalab.applet', name)
  File "/Users/jwintz/Development/openalea/core/src/core/plugin/instance.py", line 182, in instance
    instance = self.new(group, name, class_args, class_kwds)
  File "/Users/jwintz/Development/openalea/core/src/core/plugin/instance.py", line 152, in new
    return self._new(group, name, class_args, class_kwds)
  File "/Users/jwintz/Development/openalea/core/src/core/plugin/instance.py", line 118, in _new
    plugin = self.pm.item(name, group)
  File "/Users/jwintz/Development/openalea/core/src/core/manager.py", line 96, in item
    raise UnknownItemError("Item %(identifier)s not found in %(group)s" % args)
openalea.core.manager.UnknownItemError: Item TestApplet not found in oalab.applet
```

Note that the console lab works fine :-S

**Comment by pradal** [comment]
Can you send me your layout configuration file that may be located at:
~/.openalea/tissue.oaui
I suspect that a TestApplet have been defined and is not reachable.

**Comment by jwintz** [comment]
Ok, now I got it, this is the test applet we developed during the coding sprint and I have not set it up again. Everything works fine now.

Thanks.
