### ISSUE TITLE
ImportError: No module named 'util'

### ISSUE THREAD

**Issue by ThibDevos** [openalea/openalea#251]
Hi,

I'm trying to install a program I downloaded which imports openalea.deploy.
I installed openalea.deploy using pip3 and when I write
`$python3 setup.py install` in the program directory I have as error :
`Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from openalea.deploy.metainfo import read_metainfo
  File "/usr/local/lib/python3.5/dist-packages/openalea/deploy/__init__.py", line 9, in <module>
    from util import *
ImportError: No module named 'util'`
I looked in /usr/local/lib/python3.5/dist-packages/openalea/deploy/ and util.py is there.
I don't understand what's the problem

**Comment by pradal** [comment]
OpenAlea.Deploy is not uptodate on PyPi.
Please install it from github using:

pip install -U https://github.com/openalea/deploy/archive/v2.1.8.zip


Le 26/03/2020 à 11:27, ThibDev a écrit :
