### ISSUE TITLE
Save file in new project fails

### ISSUE THREAD

**Issue by gbaty** [openalea/openalea#89]
To reproduce bug:
- Create new project
- new file
- save file

```
SyntaxError: invalid syntax
Traceback (most recent call last):
  File ".../oalab/src/openalea/oalab/gui/container.py", line 262, in save_current
    self.save()
  File ".../oalab/src/openalea/oalab/gui/container.py", line 276, in save
    obj.save()
  File ".../core/src/core/data.py", line 275, in save
    with open(self.path, 'wb') as f:
IOError: [Errno 2] Aucun fichier ou dossier de ce type: path(u'.../fichier.py')
```

Explanation:
When a new project is created, it is not saved to the disk. You need to explicitly save it.
Bug is raised because as project doesn't exists, "model" doesn't exists and so file cannot be saved in.

Expected behaviour is to don't save file content but keep it in memory. To help user, a message "You must save project to save file in it" would be helpful

**Comment by gbaty** [comment]
Fixed in branch gbaty/oalab_1x
